robot_ip: "10.42.0.100"
camera_ids:
  left: "337122074882"
  right: "327122074912"
  hand: "335122272292"
# pointcloud_camera_ids:
#   front: 0
# gelsight_ids:
#   tactile_left: "GelSight Mini R0B 2BNK-CE0U: Ge"
#   tactile_right: "GelSight Mini R0B 2BG8-0H3X: Ge"
# sanwa_keyboard_ids:
#   tactile_left: /dev/hidraw6
#   tactile_right: /dev/hidraw9
